spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courses
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/courses
    user: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    baselineOnMigrate: true
    validateOnMigrate: true
  jpa:
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

secret:
  key: "7234753778214125442A472D4B6150645367566B59703373357638792F423F45"